title: "Portfolio professionnel Grégoire Beaussart"
description: "Portfolio data-analyst-supply-chain"
baseurl: "" 
url: "https://gregoiredata.github.io" 
theme: jekyll-theme-minimal

# Navigation
navbar:
  - name: "Accueil"
    link: "/"
  - name: "Portfolio professionnel"
    link: "/profil_professionnel.md"
  - name: "Projets data-analyse"
    link: "/projet.md"
  - name: "Veille métiet et technologique"
    link: "/veille_métier_technologique.md"
  - name: "Candidature offre emploi Aerosoft"
    link: "/demonstration_competences_candidature_offre_d_emploi_aerosoft.md"

# Me contacter 
contact:
  email: "beaussartgregoiredata@gmail.com"
  linkedin: "https://www.linkedin.com/in/gr%C3%A9goire-beaussart-25798893/"
