theme: jekyll-theme-cayman

title: "Portfolio professionnel"
description: "Bienvenue dans mon portfolio"
baseurl: "" 
url: "https://gregoiredata.github.io"

# Navigation
navbar:
  - name: "Accueil"
    link: "/"
  - name: "Profil professionel"
    link: "/profil_professionnel.md"
  - name: "Projets"
    link: "/projet.md"
  - name: "Veille métier et technologique"
    link: "/veille_metier_technologique.md"
  - name: "Candidature offre d'emploi Aerosoft"
    link: "/demonstration_competences_candidature_offre_d_emploi_aerosoft.md"

# Me contacter (ajouté)
contact:
  email: "beaussartgregoiredata@gmail.com"
  linkedin: "https://www.linkedin.com/in/gr%C3%A9goire-beaussart-25798893/"
