theme: jekyll-theme-cayman

title: "Portfolio professionnel Grégoire Beaussart"
description: "Portfolio data-analyst-supply-chain"
baseurl: "" 
url: "https://gregoiredata.github.io" 

# Navigation
navbar:
  - name: "Accueil"
    link: "/"
  - name: "Portfolio professionnel"
  - name: "Projets"
    link: "/projet.md"
  - name: "Veille métiet et technologique"
    link: "/veille.md"
  - name: "Candidature offre emploi Aerosoft"
    link: "/aerosoft.md"
